apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/name: hubble-generate-certs
    app.kubernetes.io/part-of: cilium
    helm.sh/chart: cilium-1.20.1
    k8s-app: hubble-generate-certs
  name: hubble-generate-certs-1c3cf8ae6a
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        k8s-app: hubble-generate-certs
    spec:
      automountServiceAccountToken: true
      containers:
        - args:
            - --ca-generate=true
            - --ca-reuse-secret
            - --ca-secret-namespace=kube-system
            - --ca-secret-name=cilium-ca
            - --ca-common-name=Cilium CA
            - --ca-enforce-validity-throughout-leaves-duration=true
          command:
            - /usr/bin/cilium-certgen
          env:
            - name: CILIUM_CERTGEN_CONFIG
              value: |
                certs:
                - name: hubble-server-certs
                  namespace: kube-system
                  commonName: "*.default.hubble-grpc.cilium.io"
                  hosts:
                  - "*.default.hubble-grpc.cilium.io"
                  usage:
                  - signing
                  - key encipherment
                  - server auth
                  - client auth
                  validity: 8760h
                - name: hubble-relay-client-certs
                  namespace: kube-system
                  commonName: "*.hubble-relay.cilium.io"
                  hosts:
                  - "*.hubble-relay.cilium.io"
                  usage:
                  - signing
                  - key encipherment
                  - client auth
                  validity: 8760h
          image: quay.io/cilium/certgen:v0.4.9@sha256:6213a4c54a1f36e14a9280765f058aaa2017550c28bc122f5b09ad146fd0da2b
          imagePullPolicy: IfNotPresent
          name: certgen
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      hostNetwork: false
      restartPolicy: OnFailure
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: hubble-generate-certs
