apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: mealie-secrets
  namespace: mealie
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTXgwTGk2OS8xT29IdWVr
        WWQyNndRRmpJN2d6L1d1SlVCU0xzRCs3YkZZCjRubnJFTzZBd2l3UVBITUJFeUxK
        eVNLa2JMWTkrd1BHMWt6azBDb1k2SzQKLS0tIFFOVEJrZWVGai8vSXZ5eWNKZjg5
        MlhmaTF6ZWNVcEZYMGYyS2c1d1NFbzgKVIZYvDUIERtoPvRTLFul1cjdCSjcFV7j
        ShLz0B/6REVn9JQ+km72ZF8NjoiS1eypUvCuqlLe2kykO5NDDcFJrg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14u8amhy8uks7vakhw3s6hpc3cvjxnnvqv636430whuncqqg46cjq5ry7pg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-06T10:22:47Z"
  mac: ENC[AES256_GCM,data:Wq5qp5aIVLiek7XSvwUXDMfbM6NalrIpSCc0YcZ6mOubz9XwONEfPaP2vjCHaWkg8RjidRZwEbe0nlhuWf4fsHy8LhefuzmDd1MCMVYfGI9jP5K2Kke4xapSvFzPnG+Yq9zkCVa73We3iqluWlJsEccPqQfzv/++LRzxD9RkIAM=,iv:GFn7ehDza/TJrNSDg/02AvazyP9u0hiPd/TTvIrSy30=,tag:oirSbptze6Hu7JPdv5FaWg==,type:str]
  version: 3.13.3
spec:
  secretTemplates:
    - name: mealie-pg
      stringData:
        password: ENC[AES256_GCM,data:aFZFTBxl/orbsqApYtja4TBXk67LcNzdPgvKOVgvg5gmal3HovhTQDLnipz7Zdc4UwKv41aMlUne4CCudEsDfGDhb8klcLWHHQwyGJTmxfiRFmk=,iv:/PDfaadrK03gFt+KGrjnqrg3g5WZ2qiwlIfwhKyStfw=,tag:tbzE8yC6BsCxxCZG/i0BuA==,type:str]
        username: ENC[AES256_GCM,data:SotK8ez0,iv:ULTkW3GYqxgHMU5FPbISlCxJWpCO9Z5sAOwqpHpCj3M=,tag:mCGsZ/d5Lk7OhoHvc2fIhg==,type:str]
    - name: mealie-oidc
      stringData:
        client-id: ENC[AES256_GCM,data:qq0+eR7oVIWliaOu5ViNT7ZAceubYTHQ6mfvIToLtmn88NJ3BbdIU1lxm57XCjMlybubdx5eS3r/EEuyW+RqD/Kaag8hmX2QFQ==,iv:p40d7hJeWd0bjlbtS1iFUwTnQY91OwOrP4vPobpZoSE=,tag:qg/tgL8cSv/DnEWhmVwpAg==,type:str]
        client-secret: ENC[AES256_GCM,data:SX+bhUxTMOZV10e/AEOSp3MQ2fFTrQf82dh1cSFJg+6z2RE=,iv:C2Z1tx75nv5hCBaVbP2MeMlTT6poSrCdduQm9zQ3eqQ=,tag:zZ4mNbyJogC0R9NRmFugmA==,type:str]
  suspend: false
