apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: kube-prometheus-prometheus
  labels:
    app: kube-prometheus-prometheus
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-prometheus-prometheus
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 90.0.0
    chart: kube-prometheus-stack-90.0.0
    heritage: Helm
    release: kube-prometheus-stack
  name: kube-prometheus-prometheus-token
  namespace: monitoring
type: kubernetes.io/service-account-token
