apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich
  namespace: immich
spec:
  cluster:
    name: immich-pg18
  extensions:
    - ensure: present
      name: vector
    - ensure: present
      name: vchord
    - ensure: present
      name: cube
    - ensure: present
      name: earthdistance
  name: immich
  owner: immich
