apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: valkey
    app.kubernetes.io/version: v3.2.0
    helm.sh/chart: immich-0.13.2
  name: immich-valkey
  namespace: immich
