apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: immich-secrets
  namespace: immich
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTXgwTGk2OS8xT29IdWVr
        WWQyNndRRmpJN2d6L1d1SlVCU0xzRCs3YkZZCjRubnJFTzZBd2l3UVBITUJFeUxK
        eVNLa2JMWTkrd1BHMWt6azBDb1k2SzQKLS0tIFFOVEJrZWVGai8vSXZ5eWNKZjg5
        MlhmaTF6ZWNVcEZYMGYyS2c1d1NFbzgKVIZYvDUIERtoPvRTLFul1cjdCSjcFV7j
        ShLz0B/6REVn9JQ+km72ZF8NjoiS1eypUvCuqlLe2kykO5NDDcFJrg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14u8amhy8uks7vakhw3s6hpc3cvjxnnvqv636430whuncqqg46cjq5ry7pg
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-30T12:00:26Z"
  mac: ENC[AES256_GCM,data:dss+BYD5keiILUL2LVYqfg6dd/puJtEwn67SnWAOG5hfeBOfH3bFKO3xSbwxJkK7XgNUCuG2ydxhfhuk7v6SoGo89uy+Rd0k4o9sHW4jWUDf4YpVymo5Hewo+M2z88oe0kMzhQ6TmLOqNw7aH7ikMAqkAzF+QArnVx+ocHkMrEw=,iv:m9j+fjAD7DY4K7RYzTWABjt+43KTxGb5bepQRXYxp48=,tag:MP0l2+vtvqAHMAJo1ZJCzQ==,type:str]
  version: 3.13.3
spec:
  secretTemplates:
    - name: immich-pg
      stringData:
        password: ENC[AES256_GCM,data:O98Rb1VFaHLLzhEEhvh/+NnqinAQnk7PkrsDsqgBuw5a8/wg+THNH1I16gKe83hkFqej,iv:ysst7/Brb20QFZGSNFVpvUOhKO2jHXKVavyV/lKBPSg=,tag:MZZcCQdSH/CrWPhF1BFXAA==,type:str]
        username: ENC[AES256_GCM,data:Vc7X6h7v,iv:KJyUM3ufZCtxCqwto4w+41JMxMADEsCictQhjb8DkQk=,tag:Zz1UaA4I1R7f6fZv+TmdHg==,type:str]
    - name: database
      stringData:
        password: ENC[AES256_GCM,data:O98Rb1VFaHLLzhEEhvh/+NnqinAQnk7PkrsDsqgBuw5a8/wg+THNH1I16gKe83hkFqej,iv:ysst7/Brb20QFZGSNFVpvUOhKO2jHXKVavyV/lKBPSg=,tag:MZZcCQdSH/CrWPhF1BFXAA==,type:str]
        user: ENC[AES256_GCM,data:yPampHr0,iv:W+fBN7qJwza5kcKIy7nLypCb06sriUOrEBRNt2FBHoU=,tag:HJCgG7cRBNHKhb9TxhQOgA==,type:str]
  suspend: false
