apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: paperless-secrets
spec:
    suspend: false
    secretTemplates:
        - name: paperless
          stringData:
            secretkey: ENC[AES256_GCM,data:a+8A5nSxQK2+Q5c8l3qXCWSsgqRsvFhpmlJSNLVPF2K+vetqUyhVdh2U/T7I0YwI6W1V,iv:+JVLsgXTQdNkQ5fAche+yjIxLdgLRkX+H7yoy20kgr8=,tag:lHVQiNEp3fHHWJFlc6jbdQ==,type:str]
            admin: ENC[AES256_GCM,data:uzQ7YpF4o8mb,iv:zhFHzmvsBbVvgZEONzdhti/FsSCjfRIJOFbetQjBKdA=,tag:qQNqWtr9dp8L+cQRv3LAow==,type:str]
            password: ENC[AES256_GCM,data:p1XB+mO/PtNqNsoRfwiNQzUorMk=,iv:s21TCKfK00W7lZWUeb1lyU4J1xELCf/hoNBxxOrgyeA=,tag:qbcp19R8m1y+77XBOGPJ4A==,type:str]
            postgresql-password: ENC[AES256_GCM,data:i44EK9yXl8nGxwDdaBNmtJ4kmqY=,iv:KVxaVMRQc2QTT1BLR7ZRoOsyZmpVGxZwe6FpoAyikjg=,tag:+KIHQAYcVo8fEx5eNZtFTA==,type:str]
            redis: ENC[AES256_GCM,data:2IlJCvTz6XRC9wANC6qabIK9pwgY6G8Rd+nywiXM0mkM5Z0VrUwFKCtjAPrqZi8+MUiVEJ61wzNeABv0Ct0dcamMrY7qIj36soua0QnpforRKu4v46Sahw==,iv:G3jHiqRt54rAozF+MPWCfHqKs9ZCzbXb8UGH20nUVD0=,tag:TZ4LmNLPZmjh+A5YZKAeag==,type:str]
            paperless-apps: ENC[AES256_GCM,data:YzMIijUAQael1cSd6lkmGkpcurjM6S/Pkevz6BsGlUOKVOL+AUU=,iv:rkZqY0bUiuYdSueMUCHi74Mu6G7TOyhrOEtBCklplVI=,tag:3yqyU0eZjW561imV4R/Kgg==,type:str]
            paperless-socialaccount-providers: ENC[AES256_GCM,data:8xmDKHmWzfRZWb2s/mIbOUhvjwfk8p9lmAsPrxDCB6OSEPb8fPN/xraSKGjB3pRvyqiEBSnzD8ePKAPK84eLR2noOdGcE+hI+kbIHgjxapmx2md0rWe83lgRGFOXHjduRx81fJlLzHSnEwms23DatuHgfBZLFJgOIBoFRgx4nmjITKo2/MgMmr8XVzGEkjtvKWH1+kQeJgrnaI86bUH2O0al+ulsceAzwnsdolgIJyOPnZUsF1x8Oo6TkKvwG8ICxjVlZOf3GkTDhcaPs9qXSgXH1PUXBCHcWTgp7oYtKvWLpMNCzqJWSxbgx8PB67L2txjmRD5hQ0r4B/Ee1mom6EYGA+ekVgvbN2hu+caH7iLhtYGCHWFcaXZMDKXREg2BozmtQB3n7wK2mR4/Y5xByN9TYkUhZsBkj/u9/O6Y7xbQWO7PJRJykz2V/QDodd72ZOr8Idv3pzAnXg3AJ+u8N8fJX+6qpgpmSn+J5lxN8x2f+i04phfJnphYX5JMMX4wQPiOxbz7TW4CJsbot7zgq4Cgv3yXqZwS0yuTG78B,iv:kT07I94j0Eg111aUcBUut9U9Url/PYQXQ1rjv9kSsOc=,tag:GdFKidhjM9P4rA0B8bm3Bw==,type:str]
        - name: paperless-pg
          stringData:
            username: ENC[AES256_GCM,data:nSbowBWvVGbD,iv:PO+a0kLExSY0zcZ63VxL3Kf1Rll59D8i7jW0//FODTc=,tag:l9f0zGHH4/+5kS9BwOckAA==,type:str]
            password: ENC[AES256_GCM,data:BuECxoKYXWcPAT3odFcrQ6RhIvc=,iv:6QDN/mZFb3IG+jN0BWSuTlMUnXbiyExHLJZACTLFd+Q=,tag:oa+0LxpzQVmNs4R9XNXYhQ==,type:str]
        - name: nextcloud
          stringData:
            url: ENC[AES256_GCM,data:8G2JU2T8vXCgnJJJrCAn4/35/aJJLCECQ3ALA/kqJB72Gd92qH4sjGDVRbsD9iduxRVgOcHAWdsCOJL4sKc=,iv:0l32fbiYUVfubao3tFlJLUKl9XMgUx2/XGWKJATFHyE=,tag:Wksag3Tt9bSPLJaDdFixaw==,type:str]
            user: ENC[AES256_GCM,data:M1DoPLIUaXt2,iv:fjYQoUK/YrEtlNUPccMHKpGKCFFcyqriunRpX0TbbRs=,tag:GPmVQr3MtcQV1ni2MSZ3Yw==,type:str]
            #ENC[AES256_GCM,data:8IDoULzFv0mTFcuimQTTBsz0gD6dKYnZvOXIZ/sJWrfhK3zN5dxDnDWhEVx96o9GVHGl77Pt1d7rcg==,iv:Ae0szHTmBFLfDEiBG8bTOQe2NTz0+oUr0Jo6h+x37Ak=,tag:mRDRhgcl7kH6pVS9XrTHGQ==,type:comment]
            password: ENC[AES256_GCM,data:xLg5XKyo2nq6d7WucfGiKFXENSz0Ao1CEGreFDC5fXJ2Z93oOYS0G6tjW8qQUJ4U,iv:a4IuV1Qd39HYIrLUSDGOUM4oZev7AwBjh1Y+C942ZTg=,tag:3gCZ9gq9L7V4VmSsssImNw==,type:str]
        - name: valkey-users
          stringData:
            default: ENC[AES256_GCM,data:zgyo0ZTgdobmFx1AlxdDRY6f+fPMqI0lOE2xqxEfHl8gLaK205yz2A==,iv:I3E9IKE1uCmld7m/oj+6b/3WlPjdRmRS6tvnf/Fh5I4=,tag:8R2UYXEtxPv/hinQQYFvVg==,type:str]
            paperless: ENC[AES256_GCM,data:aNc/g39tBxhG9hp5lfaZGnO44EUDt78YwOhDkwIt,iv:FiKdQhJoVgG2S/pkiFjEmotf+qjtuBohTlR/IDwwWfs=,tag:jO91ZoADRAJ5q1vCTDTedA==,type:str]
        - name: valkey
          stringData:
            password: ENC[AES256_GCM,data:GdhlJ8p9pr/Ipe93MAb8LzrytAc0CvAD9lyt732o,iv:ynJS7QcRJrsQbCeWA3V63By3PvQP8NYx4saLPnvQNZE=,tag:SgEnaGEZIR/8c5tVKe+lYA==,type:str]
sops:
    age:
        - recipient: age14u8amhy8uks7vakhw3s6hpc3cvjxnnvqv636430whuncqqg46cjq5ry7pg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTXgwTGk2OS8xT29IdWVr
            WWQyNndRRmpJN2d6L1d1SlVCU0xzRCs3YkZZCjRubnJFTzZBd2l3UVBITUJFeUxK
            eVNLa2JMWTkrd1BHMWt6azBDb1k2SzQKLS0tIFFOVEJrZWVGai8vSXZ5eWNKZjg5
            MlhmaTF6ZWNVcEZYMGYyS2c1d1NFbzgKVIZYvDUIERtoPvRTLFul1cjdCSjcFV7j
            ShLz0B/6REVn9JQ+km72ZF8NjoiS1eypUvCuqlLe2kykO5NDDcFJrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T05:20:29Z"
    mac: ENC[AES256_GCM,data:XWGpsF6d+LBP/Kh6hC3H+goMfTcVuNh890/k6zozjPhsbuYhxGVIr8eZD4PsFQLt/a4KcDuyfMhzQLytcg/rkofJ9Rz2KgSab+GESH4O7kZqSZ62cjRkiquYpbEiW8qKS+QWVFCh+W0IMGGiNESmOBdQl0wzU8iK1oVgfUvz/c8=,iv:LsJsYEqnO960X61Hb8C4rcdOBZGxve+/sZF0VMGNE94=,tag:Cf5N/Yd4ndfAdBCA0st+3Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
