[bar.default]
background_opacity = 0.79999998211860657
center = [ "workspaces" ]
contact_shadow = true
end = [ "notifications", "keyboard_layout", "network", "volume", "screenshot", "tray", "spacer_clock", "clock" ]
margin_edge = 0
margin_ends = 0
position = "left"
radius_bottom_left = 0
radius_bottom_right = 0
radius_top_left = 0
radius_top_right = 0
start = [ "launcher" ]
thickness = 40
widget_spacing = 15

    [bar.default.monitor.HDMI-A-1]
    enabled = false

[control_center]
shortcuts = []

[desktop_widgets]
schema_version = 2
widget_order = [
    "desktop-widget-0000000000000002",
    "desktop-widget-0000000000000004",
    "desktop-widget-0000000000000005",
    "desktop-widget-0000000000000006",
    "desktop-widget-0000000000000007",
    "desktop-widget-0000000000000008"
]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 128.0
    box_width = 320.0
    cx = 247.5
    cy = 192.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "media_player"

    [desktop_widgets.widget.desktop-widget-0000000000000003]
    box_height = 128.0
    box_width = 320.0
    cx = 247.5
    cy = 336.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000003.settings]
        stat2 = "ram_pct"

    [desktop_widgets.widget.desktop-widget-0000000000000004]
    box_height = 128.0
    box_width = 128.0
    cx = 488.0
    cy = 192.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000004.settings]
        aspect_ratio = 2.5
        background_padding = 0.0
        bands = 52.0
        centered = true
        mirrored = false
        show_when_idle = true

    [desktop_widgets.widget.desktop-widget-0000000000000005]
    box_height = 128.0
    box_width = 192.0
    cx = 600.0
    cy = 336.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000005.settings]
        color = "secondary"
        stat = "ram_pct"

    [desktop_widgets.widget.desktop-widget-0000000000000006]
    box_height = 128.0
    box_width = 192.0
    cx = 392.0
    cy = 336.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000006.settings]
        stat2 = "cpu_temp"

    [desktop_widgets.widget.desktop-widget-0000000000000007]
    box_height = 128.0
    box_width = 192.0
    cx = 183.5
    cy = 336.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000007.settings]
        shadow = true
        stat = "net_rx"
        stat2 = "net_tx"

    [desktop_widgets.widget.desktop-widget-0000000000000008]
    box_height = 128.0
    box_width = 288.0
    cx = 231.5
    cy = 480.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "weather"

        [desktop_widgets.widget.desktop-widget-0000000000000008.settings]
        background = true

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 900

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = false
    timeout = 660

[location]
address = "Drensteinfurt, Deutschland"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1", "lockscreen-login-box@DP-2" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
    box_height = 0.0
    box_width = 0.0
    cx = 1720.0
    cy = 1317.0
    output = "DP-2"
    rotation = 0.0
    type = "login_box"

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 0.0
    box_width = 0.0
    cx = 600.0
    cy = 1797.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

[osd.kinds]
bluetooth = false
brightness = false
caffeine = false
lock_keys = false
wifi = false

[shell]
font_family = "Inter"
settings_show_advanced = true

    [shell.panel]
    borders = false
    control_center_placement = "centered"
    session_placement = "centered"
    transparency_mode = "glass"
    wallpaper_placement = "centered"

    [shell.screenshot]
    directory = "/home/serowy/pictures"

    [[shell.session.actions]]
    action = "lock"
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    enabled = false
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    enabled = true
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    enabled = true
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    enabled = true
    shortcut = "5"
    variant = "destructive"

    [shell.shadow]
    direction = "center"

[theme]
builtin = "Catppuccin"
wallpaper_scheme = "m3-tonal-spot"

[wallpaper]
directory = "/home/serowy/nextcloud/Wallpapers"
transition = [ "fade" ]

    [wallpaper.automation]
    enabled = true

    [wallpaper.default]
    path = "/home/serowy/nextcloud/Wallpapers/backiee-98927.jpg"

    [wallpaper.last]
    path = "/home/serowy/nextcloud/Wallpapers/backiee-98927.jpg"

    [wallpaper.monitors.DP-2]
    path = "/home/serowy/nextcloud/Wallpapers/backiee-98927.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/serowy/nextcloud/Wallpapers/backiee-98927.jpg"

[widget.bongocat]
script = "scripts/bongocat.lua"
type = "scripted"

[widget.clock]
scale = 0.90000000000000013

[widget.keyboard_layout]
show_icon = false

[widget.spacer_clock]
length = 25
type = "spacer"

[widget.tray]
drawer = true

[widget.volume]
show_label = false

[widget.workspaces]
display = "none"
empty_color = "tertiary"
