apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: certificates-secrets
spec:
    suspend: false
    secretTemplates:
        - name: azure-acme-environment
          stringData:
            AZURE_CLIENT_SECRET: ENC[AES256_GCM,data:NSSCJZj53ob773Zn3V2Qu+DZibFcg7xyVE0ImnRukbFZGNj7SnI2KA==,iv:umvPTB/m9NoXfv2NdtdL8AcWSlEpyLhVCqX4i8ip+W4=,tag:I773ibUmKl9/9S6+YGtOWw==,type:str]
sops:
    age:
        - recipient: age14u8amhy8uks7vakhw3s6hpc3cvjxnnvqv636430whuncqqg46cjq5ry7pg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTXgwTGk2OS8xT29IdWVr
            WWQyNndRRmpJN2d6L1d1SlVCU0xzRCs3YkZZCjRubnJFTzZBd2l3UVBITUJFeUxK
            eVNLa2JMWTkrd1BHMWt6azBDb1k2SzQKLS0tIFFOVEJrZWVGai8vSXZ5eWNKZjg5
            MlhmaTF6ZWNVcEZYMGYyS2c1d1NFbzgKVIZYvDUIERtoPvRTLFul1cjdCSjcFV7j
            ShLz0B/6REVn9JQ+km72ZF8NjoiS1eypUvCuqlLe2kykO5NDDcFJrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T13:40:23Z"
    mac: ENC[AES256_GCM,data:dYPNDB0DvezFZVb3V0VLu9HzCGuZPeF7efMgNMMDHCY2PVRVn2kezGKLsTPg6cUIGQJPOjOhcBchZ+LBXBpPWqPzNjktxi2tLiTxIZLmUrlJjDERz6iu2e3KXoc5H5TKVdfCGNBVc5Xe8HQRHazDepSq4GmBFd8/KTPFdwZjU6w=,iv:sNTOIKWdAC3tuQ+lHNm8taglQn8mBvbnH9yeGoP9rwE=,tag:NGu7XavbtJ9+KEYO+thdjw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
