apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: monitoring-secrets
spec:
    suspend: false
    secretTemplates:
        - name: alertmanager-acs-secret
          stringData:
            password: ENC[AES256_GCM,data:I1uRYtMHBRjOJEgcHeP0+9a8kSYX8BWFlInrDXxTjjynjstSeFCXrw==,iv:Oac1PpD/JeBySUkWMQJmaK1efDfSU/egQMSkikIiXsQ=,tag:VKareLK3XUaOrKutSfk5SA==,type:str]
        - name: grafana
          stringData:
            admin-user: ENC[AES256_GCM,data:3BW+FlUJdA==,iv:Uns5Z+GF8c7j/pthCdYR1toZ2RWK0e03xStg3OsLsLA=,tag:HX8egN7iisoJSTdsNb6lyg==,type:str]
            admin-password: ENC[AES256_GCM,data:7eF5BpOPzxqo/ZV65IhM,iv:zg2wiYCI8Sf796ccAl7NOju38tj45ZxDglgp2+QiSBw=,tag:jKt/NeP+0omh45YvqRklRw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTXgwTGk2OS8xT29IdWVr
            WWQyNndRRmpJN2d6L1d1SlVCU0xzRCs3YkZZCjRubnJFTzZBd2l3UVBITUJFeUxK
            eVNLa2JMWTkrd1BHMWt6azBDb1k2SzQKLS0tIFFOVEJrZWVGai8vSXZ5eWNKZjg5
            MlhmaTF6ZWNVcEZYMGYyS2c1d1NFbzgKVIZYvDUIERtoPvRTLFul1cjdCSjcFV7j
            ShLz0B/6REVn9JQ+km72ZF8NjoiS1eypUvCuqlLe2kykO5NDDcFJrg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14u8amhy8uks7vakhw3s6hpc3cvjxnnvqv636430whuncqqg46cjq5ry7pg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-02T07:30:43Z"
    mac: ENC[AES256_GCM,data:WUK62atXQ2aeL/owJKoZNiNeplJ+QpAd+QBw7/jenq54azh87/UBr7AakC8mI1VOnqVOzPFFcAC4doUQTGTSbTMQCDCMw1LYz0yaFQk8AF1+PwfQ0M4eCfI+n5PVBxswb6Ao1XqL9e/+2pndlOgilTNxbgfJ4caFbW0UklW07xY=,iv:0ygqTf9GRgHBhvDYfQQMf0LBSCEsO3DhX0yeFA8TNp0=,tag:wI6YGu8wW+icshjhNl7DFQ==,type:str]
    version: 3.13.3
