# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  microsoft-edge-beta = {
    pname = "microsoft-edge-beta";
    version = "95.0.1020.14";
    src = fetchurl {
      url = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-beta/microsoft-edge-beta_95.0.1020.14-1_amd64.deb";
      sha256 = "1k95jaxmwsd24xr2m9ywrcn21mcdkpdf6845n5lbkn3jvcbzjkvv";
    };
  };
}
